# Generated by Django 5.2.7 on 2025-11-12 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_assessment_grade_gradeconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Is this the primary contact for the student?')),
                ('can_view_grades', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_view_timetable', models.BooleanField(default=True)),
                ('can_receive_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary_contact', '-created_at'],
                'indexes': [models.Index(fields=['parent', 'student'], name='academics_p_parent__8f3452_idx'), models.Index(fields=['parent', 'is_primary_contact'], name='academics_p_parent__a700ef_idx')],
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
